### ISSUE TITLE
Overwrites existing `_redirects` file

### ISSUE THREAD

**Issue by brianfryer** [fortes/metalsmith-alias#6] opened 2018-07-14 07:22 UTC
## Expected behavior:

If a Netlify `_redirects` file already exists, `metalsmith-alias` should append contents to the existing file.

## Actual behavior:

If a Netlify `_redirects` file already exists, `metalsmith-alias` replaces contents of the existing file.

**Comment by fortes** [comment] 2018-07-17 07:39
Thanks for the report, the expected behavior seems reasonable.

I'm traveling now so can't get to it, but happy to approve a pull request if you have the time

**Comment by fortes** [comment] 2018-07-17 07:41
Actually, looking at the code and changelog, the expected behavior should already be the case. Are you using the latest version?

**Comment by fortes** [comment] 2018-08-20 13:22
Closing this since I cannot reproduce (perhaps you're on an old version?). Please re-open if you're still seeing it.

**Closed as completed by fortes** 2018-08-20 13:22 UTC
